<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/24 02:54:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=84.200.193.32;port=3306;dbname=orangehrm_mysql_d',
  'username' => 'root',
  'password' => 'password',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
