<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/21 00:16:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=84.200.193.32;port=3306;dbname=orangehrm2',
  'username' => 'orangehrm',
  'password' => NULL,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
