all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=84.200.193.32;port=3306;dbname=orangehrm_mysql_d'
      username: root
      password: password
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=84.200.193.32;port=3306;dbname=test_orangehrm_mysql_d'
      username: root
      password: password